# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.pcc.odh
canonical: https://profiles.ihe.net/PCC/ODH
version: 1.0.0
name: IHE_PCC_ODH
title: "IHE FHIR Profile: Occupational Data for Health (ODH) - International"
status: active
#releaseLabel: ci-build
#releaseLabel: ballot
releaseLabel: Trial-Implementation
date: 2024-12-05
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE Patient Care Coordination Committee
  - url: https://www.ihe.net/ihe_domains/patient_care_coordination/
  - email: pcc@ihe.net
contact:
  - name: IHE Patient Care Coordination Committee  
    telecom:
      - system: email
        value: pcc@ihe.net
description: This IG covers the specific data that covers past or present jobs, usual work, employment status, retirement date and combat zone period for the subject. It also includes the past or present jobs and usual work of other household members. This IG is International scope.
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
license:  CC-BY-4.0
fhirVersion: 4.0.1
copyrightYear: 2020+

dependencies:
    us.cdc.phinvads:
        uri: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads
        id: uscdcphinvads
        version: 0.12.0

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
#  List/genetic:
#    name:  Example Amanda Alvarez 
#    description: Example Amanda Alvarez documents what an example compositoin for an Antepartum Summary should look like as well as what observations should be included within the composition. 
#    exampleBoolean: true
#    name: Genetic List
#    description: TODO
#    exampleBoolean: true
  StructureDefinition/odh-CombatZonePeriod:
    name: Combat Zone Period
    description: A Combat Zone Period Observation is a clinical statement indicating the self-reported date range(s)when a person worked in what is considered a combat zone. Both civilian workers, such as Department of Defense contractors, and military service members could have worked in combat zones. Many people who have served in the military seek care first outside of the Veterans Health Administration system. Collecting this observation can facilitate important conversations about possible related health concerns, potentially prompting referral to the Department of Veterans' Affairs (VA).
    exampleBoolean: false
  StructureDefinition/odh-Employer-extension:
    name: Employer
    description: A person or organization that hires the services of another. This contains the address of the employer, which might not be the work location.
    exampleBoolean: false
  StructureDefinition/odh-EmploymentStatus:
    name: Employment Status
    description: The self-reported current and/or historical status about a person's economic relationship to work (e.g. having one or more jobs), including start and end dates. A person's Employment Status could change over time, for example, a person could be employed following a period of choosing to not be in the labor force. Outside of ODH, the employment arrangement between an employer and a person (one job) has sometimes been referred to as a person's 'employment status.' However, in ODH, Employment Status is used to characterize a person, Work Classification is used to characterize a job, and Retirement Date is used to characterize a person as retired.
    exampleBoolean: false
  StructureDefinition/odh-OccupationalDataForHealth:
    name: Occupational Data For Health
    description: covers information about a patient's work, including some voluntary work, or a patient's household members' work. ODH is designed for the social history section of a medical record, to facilitate clinical care in multiple disciplines and delivery environments. ODH can be used for clinical decision support, population health activities and value-based care, and public health reporting.
    exampleBoolean: false
  StructureDefinition/odh-PastOrPresentJob:
    name: Past Or Present Job
    description: A Past or Present Occupation Observation is a clinical statement about the type of work done by a person in a job, as reported by that person. It includes a set of self-reported, related observations that remain associated with one-another to characterize the job and provide clinically-relevant information. It also can be used in a minor's record for the job(s) of people who share a home with the person (see optional related subject). A job is defined as a work situation, training position, or (potentially clinically-relevant) volunteer position held for a specified time period; for a given job, updates to Job Occupation, Past or Present Industry (Job Industry), Supervisory Level, or Employer would constitute a new job or volunteer position. A person can have more than one job at the same time and multiple jobs over time. Knowledge about a person's job(s) informs diagnosis and management of illness and injury; it also informs management of health in the work environment, regardless of whether a condition is work-related. While knowing about a person's current job(s) is likely to be most important, some work-related health conditions can manifest after a long latency so a history of jobs can also provide valuable information. This set of related Job observations also can provide information for public health to locate infectious disease outbreaks and intervene to prevent further illness. Public health can also use these data to analyze work-related conditions such as silicosis, pesticide poisoning, and some types of cancer to identify Occupations, Industry sectors and Employers for whom interventions are needed to mitigate risk.
    exampleBoolean: false
  StructureDefinition/odh-RetirementDate:
    name: Retirement Date
    description: A Date of Retirement Observation is a clinical statement about a self-reported date (at least year) that a person considers themselves to have 'retired'. If present, the person has retired. A person can be both retired and employed; most often, a person would be retired from one job and employed in another job.
    exampleBoolean: false
  StructureDefinition/odh-UsualWork:
    name: Usual Work
    description: A Usual Occupation Observation is a clinical statement about the type of work (paid or unpaid) done by a person for the longest amount of time during his or her life, not including voluntary work. It includes a set of self-reported, related components about the work a person performed for the longest amount of time during his or her life, regardless of the person's current job and regardless of whether or not the person performed this work for a continuous time. It also can be used in a minor's record for the Usual Work of people who share a home with the person (see optional related subject). Usual Work supports recognition of new and known chronic conditions which evolve over many years and may become evident after the person is no longer performing that type of work, e.g., some respiratory conditions and cancers. These data also are used by public health entities and medical researchers to investigate the relationship between conditions and exposures at work and illnesses, causes of death, or cancer.
    exampleBoolean: false
  ValueSet/obf-datatype-YesNoVS:
    name: Yes No VS
    description: Value set indicating yes or no (values drawn from Snomed CT), equivalent to LL361-7.
    exampleBoolean: false
  ValueSet/odf-industriesVS:
    name: industries
    description: Value set indicating the ILO industries.
    exampleBoolean: false
  ValueSet/odf-occupationVS:
    name: Occupations
    description: Value set indicating the ILO occupations.
    exampleBoolean: false
  StructureDefinition/odh-isCurrentJob-extension:
    name: ODHIsCurrentJob-extension
    description: A flag indicating if this is the person's current job (at the time the resource was last updated)
    exampleBoolean: false
  Observation/observation-odh-combat-zone-period-sample:
    name: Combat Zone Period Example
    description: This example includes a combat zone period of 1 year for patient Maya Gordon.
    exampleBoolean: false
#            <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-CombatZonePeriod
  Observation/observation-odh-employment-status-sample:
    name: Employment Status Example
    description: This example shows an employment status of 'Employed' for patient Maya Gordon.
    exampleBoolean: true
#            <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-EmploymentStatus
  Observation/observation-odh-retirement-date-sample:
    name: Retirement Date Example
    description: This example shows a retirement date for test patient Maya Gordon.
    exampleBoolean: true
 #           <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-RetirementDate
  Patient/patient-odh-maya-gordon:
    name: ODH Patient Maya Gordon
    description: This is an example of patient, Maya Gordon, that is associated with the work profile examples.
    exampleBoolean: true
  Practitioner/ex-practitioner:
    name: ODH Practitioner Simone Heps
    description: This is an example of practitioner, Simone Heps.
    exampleBoolean: true
  Observation/observation-odh-usual-work-sample:
    name: Usual Work Example
    description: Example for the Usual Work profile
    exampleBoolean: false
#            <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-UsualWork
  Composition/composition-odh-occupational-data-for-health-sample:
    name: Occupational Data Composition for Maya Gordon
    description: Complete composition example of work information for patient Maya Gordon.
    exampleBoolean: false
#            <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-OccupationalDataForHealth
  Organization/organization-odh-south-hospital:
    name: South Hospital
    description: Organization - South Hospital Example
    exampleBoolean: true
  Observation/observation-odh-past-or-present-job-sample:
    name: Past or Present Job Example
    description: This is an example of a Past or Present Job for patient, Maya Gordon. This example includes coded Occupation, Industry, Work Classification (compensation sector and employment type), Work Schedule, Weekly Work Days, Daily Work Hours, Job Duties, and Occupational Hazard.
    exampleBoolean: false
#            <exampleCanonical value="https://profiles.ihe.net/PCC/ODH/StructureDefinition/odh-PastOrPresentJob

pages:
  index.md:
    title: Occupational Data for Health (ODH) Home
    generation: markdown
  downloads.md:
    title: Download and Analysis
    generation: markdown

parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - input/resources/composition
    - input/resources/observation
    - input/resources/structuredefinition
    - input/resources/valueset
    - input/resources/patient
    - input/resources/organization
    - input/resources/practitioner
    - fsh-generated/resources
    - input/examples
  special-url: 
    - https://metadata.ilo.org/thesaurus.html
    - https://www.ilo.org/global/industries-and-sectors/health-services/lang--en/index.htm
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  autoload-resources: 'true'
  shownav: 'true'
  auto-oid-root: 1.3.6.1.4.1.19376.1.5.3.1.3.43
